---
- hosts: VMS
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Uninstall old versions
      apt: 
        name: 
          - docker 
          - docker-engine 
          - docker.io 
          - containerd runc
        state: absent
    
    - name: Update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Install Docker depedencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true
    
    - name: Creates keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
    
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: Update
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Install Docker Engine
      apt: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true
    
    - name: Create docker group
      group:
        name: docker
        state: present
    
    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes