- hosts: VMS
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
  - name: Install Docker
    include_tasks: ./general-tasks/install-docker.yaml

  - name: Install Kubectl
    include_tasks: ./general-tasks/install-kubectl.yaml





